### ISSUE TITLE
lorri watch crashes

### ISSUE THREAD

**Issue by basvandijk** [target/lorri#150]
`lorri watch` occasionally crashes for me:

```
$ lorri watch
Started
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Unrecoverable(Notify(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })))', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
```

```
$ RUST_BACKTRACE=1 lorri watch
Started
Completed(
    BuildResults {
        output_paths: OutputPaths {
            shell_gc_root: RootPath(
                "/Users/bas/Library/Caches/com.github.target.lorri.lorri.lorri/gc_roots/f4ad3016112d2f0dbb0438cf8ba2cf6f/gc_root/shell_gc_root",
            ),
        },
    },
)
Started
thread '<unnamed>' panicked at 'got more or less than one build product from logged_evaluation.nix: []', src/builder.rs:89:5
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: lorri::builder::run
   7: lorri::build_loop::BuildLoop::once
   8: lorri::build_loop::BuildLoop::forever
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: lorri::ops::watch::main
   9: lorri::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
```

I can't share my `shell.nix` since it's proprietary. I'll try to minimize it.

**Comment by gilligan** [comment]
@basvandijk while this definitely shouldn't be happening - is there a reason that you are using `lorri watch` instead of the now preferred `lorri daemon` ?

**Comment by basvandijk** [comment]
Hey Tobias! I was following the [tutorial](https://github.com/target/lorri/tree/master/example) which still seems to recommend `lorri watch`. For actual use I think `lorri daemon` is indeed the better choice.

**Comment by Profpatsch** [comment]
Did you install lorri by running 

```
$ git clone -b rolling-release https://github.com/target/lorri.git
$ cd lorri
$ nix-env -if .
```

as described in the `README`?

Or did you use the `default.nix` in the checkout of the lorri master branch?

**Comment by mbrgm** [comment]
@Profpatsch I'm facing the same issue while using lorri daemon and installed lorri using the method you described. Do you need more information?

**Comment by Profpatsch** [comment]
@mbrgm Can you try on current master? The PR we merged should have solved a bunch of problems.

**Comment by mbrgm** [comment]
@Profpatsch Sorry for the delay, could not manage to test it until now. It is working now when I'm running `lorri daemon` from the shell. But from a systemd user service, I was getting the following backtrace:

```
Started
thread '<unnamed>' panicked at 'Unrecoverable error!
Build(
    Instantiate(
        Os {
            code: 2,
            kind: NotFound,
            message: "No such file or directory"
        }
    )
)', src/build_loop.rs:84:56
stack backtrace:
   0:     0x560c8341dc1f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hfad0220813d5e5c3
   1:     0x560c8342e657 - std::sys_common::backtrace::print::h16017ddc8b354e39
   2:     0x560c834214c3 - std::panicking::default_hook::{{closure}}::h8b06d3b8a7138cc5
   3:     0x560c83421243 - std::panicking::default_hook::h8cac4830452b35df
   4:     0x560c83421bbf - std::panicking::rust_panic_with_hook::hd32c26e1600a179b
   5:     0x560c83421751 - std::panicking::continue_panic_fmt::h24b78f7279f44cef
   6:     0x560c8342169e - std::panicking::begin_panic_fmt::h98672d172280200e
   7:     0x560c832a6566 - lorri::build_loop::BuildLoop::forever::h107a54d9d12e731b
   8:     0x560c832a8d73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6de3911e47385787
   9:     0x560c832b79d8 - std::panicking::try::do_call::ha622cd5ff1ae34b0
  10:     0x560c83439499 - __rust_maybe_catch_panic
  11:     0x560c832b1a92 - <F as alloc::boxed::FnBox<A>>::call_box::hed14b3946e261b17
  12:     0x560c8341c9ed - std::sys_common::thread::start_thread::h09a6bf95952964d1
  13:     0x560c834278e5 - std::sys::unix::thread::Thread::new::thread_start::h165ad4e27a9c9315
  14:     0x7fc0a1348ef6 - start_thread
  15:     0x7fc0a106822e - __GI___clone
  16:                0x0 - <unknown>
```

I ran strace on the process and found the following

```
3966520 execve("/usr/local/bin/nix-instantiate", ["nix-instantiate", "-vv", "--add-root", "/tmp/.tmpbtAkMM/result", "--indirect", "--argstr", "runTimeClosure", "/nix/store/1manqjxzqpriw9hq5lfql"..., "--argstr", "src", "/home/myuser/repos/myproject"..., "--", "/home/myuser/.cache/lorri/cas/4a"...], 0x56085ccd1990 /* 19 vars */) = -1 ENOENT (No such file or directory)
3966520 execve("/usr/bin/nix-instantiate", ["nix-instantiate", "-vv", "--add-root", "/tmp/.tmpbtAkMM/result", "--indirect", "--argstr", "runTimeClosure", "/nix/store/1manqjxzqpriw9hq5lfql"..., "--argstr", "src", "/home/myuser/repos/myproject"..., "--", "/home/myuser/.cache/lorri/cas/4a"...], 0x56085ccd1990 /* 19 vars */) = -1 ENOENT (No such file or directory)
```

So it appears that lorri cannot find `nix-instantiate`. After adding the nix default profile bin directory as well as a proper `NIX_PATH` to the systemd unit's environment, it finally worked as expected:

```
[Unit]
ConditionUser=!@system
Description=Lorri Build Daemon
After=lorri.socket
Wants=lorri.socket

[Service]
ExecStart=%h/.nix-profile/bin/lorri daemon
PrivateTmp=true
ProtectSystem=strict
Restart=on-failure
WorkingDirectory=%h
Environment=PATH=/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=NIX_PATH=nixpkgs=%h/repos/nixpkgs
```

Hope this information helps. Thank you for fixing the other issue!

**Comment by Profpatsch** [comment]
> Hope this information helps. Thank you for fixing the other issue!

Thank you for the detailed report!

Unfortunately, the `std::io::ErrorKind::NotFound` message always lacks the filename unless the programmer manually matches and adds it, which I’ve done in: https://github.com/target/lorri/pull/174
