### ISSUE TITLE
Test "trivial_watch_whole_directory" is flaky

### ISSUE THREAD

**Issue by curiousleo** [target/lorri#247]
This build failure occurred on a very innocent PR: https://github.com/target/lorri/pull/246

https://travis-ci.org/target/lorri/jobs/618236153#L958

```
---- watch::tests::trivial_watch_whole_directory stdout ----

thread 'watch::tests::trivial_watch_whole_directory' panicked at 'assertion failed: file_changed(&watcher, "foo")', src/watch.rs:288:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39

   1: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:71

   2: std::panicking::default_hook::{{closure}}

             at src/libstd/sys_common/backtrace.rs:59

             at src/libstd/panicking.rs:197

   3: std::panicking::default_hook

             at src/libstd/panicking.rs:208

   4: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:474

   5: std::panicking::begin_panic

             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:408

   6: lorri::watch::tests::trivial_watch_whole_directory

             at src/watch.rs:288

   7: lorri::watch::tests::trivial_watch_whole_directory::{{closure}}

             at src/watch.rs:279

   8: core::ops::function::FnOnce::call_once

             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/ops/function.rs:231

   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702

  10: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:87

  11: test::run_test::run_test_inner::{{closure}}

             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:272

             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:388

             at src/libtest/lib.rs:1468

failures:

    watch::tests::trivial_watch_whole_directory

test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Profpatsch** [comment]
Did the merged PR lead to fixing this issue?

**Comment by curiousleo** [comment]
> Did the merged PR lead to fixing this issue?

No, #247 just improved the assertion message.
