### ISSUE TITLE
Lorri shell fails to build with Ansible

### ISSUE THREAD

**Issue by berbiche** [target/lorri#414]
**Describe the bug**

Given the following `shell.nix`:

``` nix
let
  # 2020-05-29
  rev = "https://github.com/NixOS/nixpkgs/archive/135073a87b7e2c631739f4ffa016e1859b1a425e.tar.gz";
  pkgs = import (builtins.fetchTarball rev) { };
in
pkgs.mkShell {
  buildInputs = [ pkgs.ansible ];
  shellHook = ''
    ansible --version
  '';
}
```

lorri should be able to build the shell, but fails because Ansible tries to write to `/homeless-shelter/.ansible/tmp`

**To Reproduce**

1. Observe `nix-shell` not having any issues fetching/building Ansible

``` console
$ nix-shell
ansible 2.9.9
  config file = None
  configured module search path = ['/home/nicolas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible
  executable location = /nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 06:34:06) [GCC 9.3.0]

[nix-shell:/tmp/tmp.aLYH9g19MN]$
```

2. Try with `lorri shell`

``` console
$ lorri shell
Jun 03 17:25:30.445 ERRO Build failed. No cached environment available.
Build error: Nix process returned exit code 100.
  $ "nix-build" "--out-link" "/tmp/.tmpuB85jr/result" "--" "/tmp/.tmpm21XX7/result"
these derivations will be built:
  /nix/store/0gc3hz85gf13ddcnnhz975vk79napr8b-lorri-wrapped-project-nix-shell.drv
building '/nix/store/0gc3hz85gf13ddcnnhz975vk79napr8b-lorri-wrapped-project-nix-shell.drv'...
Unhandled error:
 Traceback (most recent call last):
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
    os.makedirs(b_rpath, mode)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/homeless-shelter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 559, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 503, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 122, in ensure_type
    makedirs_safe(value, 0o700)
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/homeless-shelter/.ansible/tmp): [Errno 13] Permission denied: b'/homeless-shelter'


Traceback (most recent call last):
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
    os.makedirs(b_rpath, mode)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/homeless-shelter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 559, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 503, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 122, in ensure_type
    makedirs_safe(value, 0o700)
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/homeless-shelter/.ansible/tmp): [Errno 13] Permission denied: b'/homeless-shelter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/bin/.ansible-wrapped", line 63, in <module>
    import ansible.constants as C
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/constants.py", line 174, in <module>
    config = ConfigManager()
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 291, in __init__
    self.update_config_data()
  File "/nix/store/6f2i8f14galhv63326k4lv33p5yvamj8-python3.7-ansible-2.9.9/lib/python3.7/site-packages/ansible/config/manager.py", line 571, in update_config_data
    raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e)
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/homeless-shelter/.ansible/tmp): [Errno 13] Permission denied: b'/homeless-shelter'

builder for '/nix/store/0gc3hz85gf13ddcnnhz975vk79napr8b-lorri-wrapped-project-nix-shell.drv' failed with exit code 1
error: build of '/nix/store/0gc3hz85gf13ddcnnhz975vk79napr8b-lorri-wrapped-project-nix-shell.drv' failed

```

**Expected behavior**

Lorri should be able to build the shell.

**Metadata**

```console
$ lorri info
lorri version: 1.0
```

```console
$ uname -a
Linux g-word 5.6.15 #1-NixOS SMP Wed May 27 15:48:31 UTC 2020 x86_64 GNU/Linux
```

**Additional context**

Tested on both master (3d5eb131a73d72963cb3ee0eee7ac0eca5321254) and release 1.0.

**Comment by berbiche** [comment]
Turns out the issue is that the user (nixbld) that runs commands for the `shellHook` within `lorri` can only write to world-writable directories such as `/tmp`.

When invoking `ansible` for the first time, it creates files in the user's `$HOME`.

I removed the call to `ansible --version` within the `shellHook` and the problem was gone.

@Profpatsch is there anyway for the `shellHook` to _not_ be executed in the context of the `nixbld` user but that of the user?
